name: bit_transit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  go_router: 15.1.2
  flutter_bloc: 9.1.1
  equatable: 2.0.7
  enum_to_string: 2.2.1
  dio: 5.9.0
  shared_preferences: 2.5.3
  device_info_plus: 11.3.0
  json_annotation: 4.9.0
  freezed: 2.5.7
  freezed_annotation: 2.4.4
  cached_network_image: 3.4.1
  intl: 0.19.0
  flutter_localization: 0.3.3
  retrofit: 4.5.0
  retrofit_generator: 9.1.5
  flutter_gen_runner: 5.10.0
  logger: 2.6.0
  overlay_support: 2.1.0
  sizer: 3.1.3
  flutter_animate: 4.5.2
  flutter_svg: 2.1.0
  permission_handler_platform_interface: 4.3.0
  geolocator_platform_interface: 4.2.6
  geocoding_platform_interface: 3.2.0
  geocoding: 4.0.0
  permission_handler: 12.0.1
  flutter_timezone: 4.1.1
  network_info_plus: ^7.0.0
  package_info_plus: ^9.0.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.13
  json_serializable: 6.9.0
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  assets:
    exclude:
      - assets/flags/**


  # Optional
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Sf-pro-display
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBLACKITALIC.otf
          weight: 900
          style: italic

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.otf
          weight: 700

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYHEAVYITALIC.otf
          weight: 800
          style: italic

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYLIGHTITALIC.otf
          weight: 300
          style: italic

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.otf
          weight: 500

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.otf
          weight: 400

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYSEMIBOLDITALIC.otf
          weight: 600
          style: italic

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYTHINITALIC.otf
          weight: 200
          style: italic

        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYULTRALIGHTITALIC.otf
          weight: 200
          style: italic



    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900

        - asset: assets/fonts/Inter/Inter-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Inter/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700

        - asset: assets/fonts/Inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500

        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400

        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300

        - asset: assets/fonts/Inter/Inter-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Inter/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100

        - asset: assets/fonts/Inter/Inter-ThinItalic.ttf
          weight: 100
          style: italic
flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/gen # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
    project_id: # Get it from the https://app.localizely.com/projects page.
    branch: # Get it from the "Branches" page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
    upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
    upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
    download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
    download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false
































